### ISSUE TITLE
Problems with local install 

### ISSUE THREAD

**Issue by stefania11** [ColeTownsend/Balzac-for-Jekyll#20]
Hi Cole,

I am facing problems with the local install. I am afraid I didn't understood the following instruction:
"When working locally comment out url or else you will get a bunch of broken links because they are absolute and prefixed with {{ site.url }} in the various _includes and _layouts. Just remember to uncomment url when building for deployment or pushing to gh-pages..."

Which url? Could you pls provide a screenshot?

Thank you!

**Comment by ColeTownsend** [comment]
This would be in the _config.yml I believe. I've changed my workflow a little bit so this is no longer present in the config.yml.




Try running jekyll with a new baseurl, like jekyll serve --baseurl localhost:3000




http://jekyllrb.com/docs/configuration/




— Cole  ________________________________ 

Phone: 716-697-4252 Skype: cole.n.townsend 

Twitter: http://twitter.com/twnsndco
