### ISSUE TITLE
jekyll build and serve error

### ISSUE THREAD

**Issue by maestro4u** [ColeTownsend/Balzac-for-Jekyll#26]
After installing rails this morning, I can't access jekyll following blow.

HoonKim-ui-MacBook-Pro:maestro4u.github.io hoonkim$ jekyll serve --watch
error: undefined method `value' for #<Psych::Nodes::Document:0x007fa82d197f80>. Use --trace to view backtrace

But I enjoyed my blog until yesterday.
How should I do?

**Comment by maestro4u** [comment]
HoonKim-ui-MacBook-Pro:maestro4u.github.io hoonkim$ jekyll serve --trace
/Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/safe_yaml-0.7.1/lib/safe_yaml/syck_resolver.rb:6:in `resolve_node': undefined method `value' for #<Psych::Nodes::Document:0x007fb1a50455e8> (NoMethodError)
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/safe_yaml-0.7.1/lib/safe_yaml.rb:69:in `safe_load'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/safe_yaml-0.7.1/lib/safe_yaml.rb:73:in `block in safe_load_file'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/safe_yaml-0.7.1/lib/safe_yaml.rb:73:in `open'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/safe_yaml-0.7.1/lib/safe_yaml.rb:73:in `safe_load_file'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/jekyll-1.1.2/lib/jekyll/configuration.rb:119:in `read_config_file'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/jekyll-1.1.2/lib/jekyll/configuration.rb:144:in `block in read_config_files'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/jekyll-1.1.2/lib/jekyll/configuration.rb:143:in `each'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/jekyll-1.1.2/lib/jekyll/configuration.rb:143:in `read_config_files'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/jekyll-1.1.2/lib/jekyll.rb:74:in `configuration'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/jekyll-1.1.2/bin/jekyll:95:in `block (2 levels) in <top (required)>'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/commander-4.1.4/lib/commander/command.rb:180:in `call'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/commander-4.1.4/lib/commander/command.rb:180:in `call'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/commander-4.1.4/lib/commander/command.rb:155:in `run'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/commander-4.1.4/lib/commander/runner.rb:402:in `run_active_command'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/commander-4.1.4/lib/commander/runner.rb:78:in `run!'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/commander-4.1.4/lib/commander/delegates.rb:7:in `run!'
	from /Users/hoonkim/GitHub/maestro4u.github.io/vendor/bundle/ruby/2.2.0/gems/commander-4.1.4/lib/commander/import.rb:10:in `block in <top (required)>'
HoonKim-ui-MacBook-Pro:maestro4u.github.io hoonkim$

**Comment by ColeTownsend** [comment]
Hi Hoon, I would try and `gem cleanup` `rm Gemfile.lock` and if that doesn't fix it, install a different version of safe_yaml.






— Cole  ________________________________ 

Phone: 716-697-4252 Skype: cole.n.townsend 

Twitter: http://twitter.com/twnsndco

**Comment by saadq** [comment]
I just had the same issue, doing `gem cleanup` and `rm Gemfile.lock` worked for me, thanks!
