### ISSUE TITLE
You use the wrong license

### ISSUE THREAD

**Issue by victorbjorklund** [ColeTownsend/Balzac-for-Jekyll#28]
I just wanted to bring to you attention that using the MIT license gives anyone the right to resell and do anything else with the theme. It seems from your text that you don't want to grant people that right so you should probably stop using the MIT license

From the MIT license agreement to this project:

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

I don't intend to resell you theme or anything. I just wanted to bring it to your attention in case you missed it.

**Comment by ColeTownsend** [comment]
@victorbjorklund just saw this, thank you!
