### ISSUE TITLE
Loading Calendas webfont?

### ISSUE THREAD

**Issue by whanley** [ColeTownsend/Balzac-for-Jekyll#32]
Hi, I'm using the Balzac theme--thanks! Italics are not rendering in the Calendas font--I want to buy and install the webfont, but I don't know how to install it. Can you help?
Thanks, Will

**Comment by ColeTownsend** [comment]
This involves creating a web font CSS file and loading it, I recommend looking at font squirrel and reading a tutorial on how to add a web font to a site.
