### ISSUE TITLE
Work on previous page / next page for articles page

### ISSUE THREAD

**Issue by mfjgo** [ColeTownsend/Balzac-for-Jekyll#34]
It would be great to have the main articles page have the ability to link to subsequent pages of articles (for those times when the blog has many articles more than the five or so that are highlighted on the main articles page).

**Comment by ColeTownsend** [comment]
Cheers Mark! I'll take a dive this weekend. I think this would be a nice option to have.

**Comment by marcopolojohnson** [comment]
Cole,

Thanks for writing back. Yes, I’m so grateful for your willingness to try this. As I said, this slight increase in the theme’s features won’t require destroying its currently spacious loveliness. Please let me know what I can do to help (if anything).

Mark Johnson
______________________
mark.f.johnson@icloud.com
