### ISSUE TITLE
How do I add mathjax support correctly?

### ISSUE THREAD

**Issue by joshfpedro** [ColeTownsend/Balzac-for-Jekyll#40]
- I added mathjax script source to head.html in _includes.

- My layout for first-post is post-no-feature and has includes head.html

- I entered equation in first-post under header "Mathjax Test" but this resulted in no equation being displayed.

- How do I resolve this?

**Comment by ColeTownsend** [comment]
Hey @joshfpedro – If you link me to your live site I can take a look
